---
- name: latest Apache version installed
  yum:
    name: httpd
    state: latest
- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started
- name: deploy content
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - reload-apache
